name: Remove untagged images from registry

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  remove_untagged_images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Delete all containers from repository without tags
        uses: dataaxiom/ghcr-cleanup-action@main
        with:
          delete-untagged: true
          token: ${{ secrets.PACKAGE_CLEANUP_TOKEN }}
          expand-packages: true
          package: "*"
