name: Close my stale PRs

on:
  schedule:
    - cron: "30 14 * * *"

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Only show what would happen (no closing)"
        required: false
        type: boolean
        default: true

jobs:
  close-stale-prs:
    runs-on: ubuntu-slim

    steps:

      - name: Authenticate gh
        run: echo "${{ secrets.CLOSE_MY_STALE_PR_TOKEN }}" | gh auth login --with-token

      - name: Close stale PRs
        env:
          EXCLUDED_REPOS: ${{ vars.CMSP_EXCLUDED_REPOS }} #space-separated list of repos to exclude (owner/repo) [This env was configured in the repository variables.]
          DAYS: ${{ vars.CMSP_DAYS_BEFORE_CLOSE || 30 }} #days before closing a PR [This env was configured in the repository variables]
          DRY_RUN: ${{ inputs.dry_run || false }}
          REPOSITORY_OWNER: "${{ github.repository_owner }}" 
        run: |
          echo "Dry run mode: $DRY_RUN"
          echo "Fetching PRs..."

          gh search prs --author=@me --state=open --json url,updatedAt,repository,isDraft,isLocked \
          | jq -c '.[]' \
          | while read pr; do

              url=$(echo "$pr" | jq -r '.url')
              updated=$(echo "$pr" | jq -r '.updatedAt')
              repo=$(echo "$pr" | jq -r '.repository.nameWithOwner')
              repo_owner=$(echo "$repo" | awk -F/ '{print $1}')
              is_draft=$(echo "$pr" | jq -r '.isDraft')
              is_locked=$(echo "$pr" | jq -r '.isLocked')

              # Exclude checks
              if [ "$repo_owner" = "$REPOSITORY_OWNER" ]; then
                echo "Skipping PR in my own repo: $url"
                continue
              fi
              if echo "$EXCLUDED_REPOS" | grep -qw "$repo"; then
                echo "Skipping excluded repo: $repo"
                continue
              fi
              if [ "$is_locked" = "true" ]; then
                echo "Skipping locked PR: $url"
                continue
              fi
              if [ "$is_draft" = "true" ]; then
                echo "Skipping draft PR: $url"
                continue
              fi

              # Age calculation
              updated_ts=$(date -d "$updated" +%s)
              now_ts=$(date +%s)
              diff_days=$(( (now_ts - updated_ts) / 86400 ))

              echo "PR: $url | Last update: $diff_days days ago"

              if [ "$diff_days" -ge "$DAYS" ]; then
                if [ "$DRY_RUN" = "true" ]; then
                  echo "[DRY RUN] Would close PR: $url"
                else
                  echo "Closing PR: $url"
                  gh pr close "$url"
                fi
              fi

          done
